### ISSUE TITLE
matomo_tracking_embed doesn't capture the <noscript> tag

### ISSUE THREAD

**Issue by wioux** [EFForg/eff_matomo#4]

**Comment by vbrown608** [comment]
Let me know if I'm missing something - I think it's captured here https://github.com/EFForg/eff_matomo/blob/master/lib/matomo/view_helpers.rb#L14-L16

(It gets replaced on load if you've got js enabled.)

**Comment by wioux** [comment]
Whoops sorry -- to be more clear, the noscript tag needs to be `+`d together with the script tag that follows, since `content_tag` doesn't capture everything from the block, only the return value.

**Comment by vbrown608** [comment]
Ahh got it! Fixed.
